-- MySQL Script generated by MySQL Workbench
-- Fri 14 Oct 2022 16:36:05 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oficina` ;

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficina` ;
USE `oficina` ;

-- -----------------------------------------------------
-- Table `oficina`.`Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Equipe` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Equipe` (
  `idEquipe` INT NOT NULL AUTO_INCREMENT,
  `nomeEquipe` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Mecanico` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Mecanico` (
  `idMecanico` INT NOT NULL AUTO_INCREMENT,
  `idEquipe` INT NOT NULL,
  `nomeMecanico` VARCHAR(100) NULL,
  `endereco` VARCHAR(245) NULL,
  `especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idMecanico`, `idEquipe`),
  INDEX `fk_Mecanico_Equipe_idx` (`idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Equipe`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `oficina`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Veiculo` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Veiculo` (
  `idCliente` INT NOT NULL,
  `renavan` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`, `renavan`),
  CONSTRAINT `fk_Veiculo_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `oficina`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Ordem_de_Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oficina`.`Ordem_de_Servico` ;

CREATE TABLE IF NOT EXISTS `oficina`.`Ordem_de_Servico` (
  `idCliente` INT NOT NULL,
  `renavan` VARCHAR(45) NOT NULL,
  `idEquipe` INT NOT NULL,
  `dataEmissao` VARCHAR(45) NULL,
  `dataEntrega` VARCHAR(45) NULL,
  `status` ENUM('NOVO', 'CANCELADO', 'AVALIADO', 'APROVADO', 'CONCLUIDO') NULL DEFAULT 'NOVO',
  PRIMARY KEY (`idCliente`, `renavan`, `idEquipe`),
  INDEX `fk_Ordem_de_Servico_Veiculo1_idx` (`idCliente` ASC, `renavan` ASC) VISIBLE,
  INDEX `fk_Ordem_de_Servico_Equipe1_idx` (`idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_de_Servico_Veiculo1`
    FOREIGN KEY (`idCliente` , `renavan`)
    REFERENCES `oficina`.`Veiculo` (`idCliente` , `renavan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_de_Servico_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `oficina`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
